# Generated by Django 5.2.10 on 2026-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0041_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='address',
            field=models.TextField(null=False, max_length=400),
        ),
    ]
