# Generated by Django 5.2.10 on 2026-01-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0043_alter_demo_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
