# Generated by Django 5.2.10 on 2026-01-28 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0044_delete_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
