# Generated by Django 5.2.10 on 2026-01-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0046_alter_cart_created_at_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
