# Generated by Django 5.2.10 on 2026-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0047_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardholdername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
