# Generated by Django 5.2.10 on 2026-01-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0048_order_cardholdername'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
    ]
