# Generated by Django 5.2.10 on 2026-02-03 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0049_ad_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userimages/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup', to=settings.AUTH_USER_MODEL),
        ),
    ]
