# Generated by Django 5.2.10 on 2026-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0051_alter_ad_id_alter_cart_id_alter_cartitems_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main-slider-image/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
