# Generated by Django 5.2.10 on 2026-02-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0052_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='second-slider-image/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
