# Generated by Django 5.2.10 on 2026-02-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0053_slider2'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider2',
            name='first_line_text',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='slider2',
            name='second_line_text',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
