# Generated by Django 5.2.10 on 2026-02-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0054_slider2_first_line_text_slider2_second_line_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider2',
            name='first_line_text',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='slider2',
            name='second_line_text',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
