# Generated by Django 5.2.10 on 2026-02-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0055_alter_slider2_first_line_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider2',
            name='first_line_text',
            field=models.TextField(default='demo', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider2',
            name='second_line_text',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
