# Generated by Django 5.2.10 on 2026-02-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0056_alter_slider2_first_line_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_text', models.TextField(max_length=150)),
                ('second_line_text', models.TextField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='slider2',
            name='first_line_text',
        ),
        migrations.RemoveField(
            model_name='slider2',
            name='second_line_text',
        ),
    ]
