# Generated by Django 5.2.10 on 2026-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0057_slider_content_remove_slider2_first_line_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_content',
            name='first_line_text',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='slider_content',
            name='second_line_text',
            field=models.TextField(max_length=250),
        ),
    ]
