# Generated by Django 5.2.10 on 2026-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0062_alter_slider_content_first_line_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.TextField(max_length=100)),
                ('page_url', models.URLField(verbose_name='Page URL')),
            ],
        ),
    ]
