# Generated by Django 5.2.10 on 2026-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0063_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='page_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='page_url',
            field=models.CharField(max_length=200, verbose_name='Page URL'),
        ),
    ]
