# Generated by Django 5.2.10 on 2026-02-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0064_alter_navbar_page_name_alter_navbar_page_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='navbar',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
