# Generated by Django 5.2.10 on 2026-02-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0065_alter_navbar_options_navbar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
