# Generated by Django 5.2.10 on 2026-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0066_alter_navbar_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
