# Generated by Django 5.2.10 on 2026-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0067_alter_navbar_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(upload_to='Supported-company-image/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
