# Generated by Django 5.2.10 on 2026-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0068_supportedcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportedcompany',
            options={'ordering': ['company_order']},
        ),
        migrations.AddField(
            model_name='supportedcompany',
            name='company_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
