# Generated by Django 5.2.10 on 2026-02-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0069_alter_supportedcompany_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_Link_page_name', models.CharField(max_length=100)),
                ('quick_Link_page_url', models.CharField(max_length=200, verbose_name='Page URL')),
                ('quick_Link_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['quick_Link_order'],
            },
        ),
    ]
