# Generated by Django 5.2.10 on 2026-02-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0070_quicklink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['quick_link_order']},
        ),
        migrations.RenameField(
            model_name='quicklink',
            old_name='quick_Link_order',
            new_name='quick_link_order',
        ),
        migrations.RenameField(
            model_name='quicklink',
            old_name='quick_Link_page_name',
            new_name='quick_link_page_name',
        ),
        migrations.RenameField(
            model_name='quicklink',
            old_name='quick_Link_page_url',
            new_name='quick_link_page_url',
        ),
    ]
