# Generated by Django 5.2.10 on 2026-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0071_alter_quicklink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'ordering': ['q_order']},
        ),
        migrations.RenameField(
            model_name='quicklink',
            old_name='quick_link_order',
            new_name='q_order',
        ),
        migrations.RenameField(
            model_name='quicklink',
            old_name='quick_link_page_name',
            new_name='q_page_name',
        ),
        migrations.RemoveField(
            model_name='quicklink',
            name='quick_link_page_url',
        ),
        migrations.AddField(
            model_name='quicklink',
            name='q_page_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
