# Generated by Django 5.2.10 on 2026-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0073_alter_ad_id_alter_cart_id_alter_cartitems_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('slider_main', 'Main Slider'), ('slider_second', 'Second Slider'), ('slider_content', 'Slider Content'), ('navbar', 'Navbar'), ('supported_company', 'Supported Company'), ('quick_link', 'Quick Link')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='QuickLink',
        ),
        migrations.DeleteModel(
            name='slider',
        ),
        migrations.DeleteModel(
            name='Slider2',
        ),
        migrations.DeleteModel(
            name='Slider_content',
        ),
        migrations.DeleteModel(
            name='SupportedCompany',
        ),
    ]
