# Generated by Django 5.2.10 on 2026-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0074_cmscontent_delete_navbar_delete_quicklink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_url', models.CharField(max_length=200, verbose_name='Page URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_page_name', models.CharField(max_length=100)),
                ('q_page_url', models.CharField(max_length=200)),
                ('q_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['q_order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main-slider-image/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='second-slider-image/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slider_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_text', models.TextField(max_length=500)),
                ('second_line_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(upload_to='Supported-company-image/')),
                ('is_active', models.BooleanField(default=False)),
                ('company_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['company_order'],
            },
        ),
        migrations.DeleteModel(
            name='CMSContent',
        ),
    ]
