# Generated by Django 5.2.10 on 2026-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0075_navbar_quicklink_slider_slider2_slider_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_image', models.ImageField(upload_to='Information_image/')),
                ('info_title', models.TextField(max_length=50)),
                ('info_text', models.TextField(max_length=250)),
                ('info_button_url', models.TextField(max_length=50)),
            ],
        ),
    ]
