# Generated by Django 5.2.10 on 2026-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0076_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='info_button_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='informations',
            name='info_text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='informations',
            name='info_title',
            field=models.CharField(max_length=50),
        ),
    ]
