# Generated by Django 5.2.10 on 2026-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0077_alter_informations_info_button_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'ordering': ['info_order']},
        ),
        migrations.AddField(
            model_name='informations',
            name='info_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
