# Generated by Django 5.2.10 on 2026-02-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0078_alter_informations_options_informations_info_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='informations',
            old_name='info_order',
            new_name='order',
        ),
    ]
