# Generated by Django 5.2.10 on 2026-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0079_alter_informations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
