# Generated by Django 5.2.10 on 2026-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0080_alter_informations_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informations',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='informations',
            old_name='order',
            new_name='position',
        ),
    ]
