# Generated by Django 5.2.10 on 2026-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0082_tractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tractor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='Teactor_page_image/')),
                ('tractor_name', models.TextField(max_length=50)),
                ('Engine', models.TextField(max_length=200)),
                ('Transmission', models.TextField(max_length=200)),
                ('Hydraulics', models.TextField(max_length=200)),
                ('Brake', models.TextField(max_length=200)),
                ('Steering', models.TextField(max_length=200)),
                ('FuelTank', models.TextField(max_length=200)),
                ('Tyres', models.TextField(max_length=200)),
                ('Build', models.TextField(max_length=200)),
                ('Price', models.TextField(max_length=200)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Tractor',
        ),
    ]
