# Generated by Django 5.2.10 on 2026-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0083_tractor_model_delete_tractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor_model',
            name='Brake',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Build',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Engine',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='FuelTank',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Hydraulics',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Steering',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Transmission',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='Tyres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tractor_model',
            name='tractor_name',
            field=models.CharField(max_length=50),
        ),
    ]
