# Generated by Django 5.2.10 on 2026-02-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0084_alter_tractor_model_brake_alter_tractor_model_build_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tractor_model',
            new_name='Tractor_Page',
        ),
    ]
