# Generated by Django 5.2.10 on 2026-02-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0085_rename_tractor_model_tractor_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Primary Tillage', 'Primary Tillage'), ('Secondary Tillage', 'Secondary Tillage'), ('Primary / Secondary', 'Primary / Secondary'), ('Seedbed Preparation', 'Seedbed Preparation'), ('Deep Tillage', 'Deep Tillage'), ('Transport', 'Transport')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='equipment/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
