# Generated by Django 5.2.10 on 2026-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0088_alter_equipment_name_alter_equipment_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='slug',
        ),
        migrations.AddField(
            model_name='equipment',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
