# Generated by Django 5.2.10 on 2026-02-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0089_alter_equipment_options_remove_equipment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
