# Generated by Django 5.2.10 on 2026-02-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0090_alter_equipment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feauter_1', models.CharField(max_length=200)),
                ('feauter_2', models.CharField(max_length=200)),
                ('feauter_3', models.CharField(max_length=200)),
                ('feauter_4', models.CharField(max_length=200)),
                ('weight_range', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ox_page/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
