# Generated by Django 5.2.10 on 2026-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0091_ox'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroChemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('pack_size', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='agrochemicals/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
