# Generated by Django 5.2.10 on 2026-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0092_agrochemical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nutrient', models.CharField(max_length=200)),
                ('best_for', models.CharField(max_length=200)),
                ('benefits', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Fertilizer/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
