# Generated by Django 5.2.10 on 2026-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0093_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprayPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=100)),
                ('tagline_color', models.CharField(max_length=50)),
                ('operation_type', models.CharField(max_length=100)),
                ('operation_color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('feature_3', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='spray-pump/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('pressure', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
