# Generated by Django 5.2.10 on 2026-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0094_spraypump'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Agriculture_guidance/')),
                ('crop_name', models.CharField(max_length=300)),
                ('crop_season', models.CharField(max_length=300)),
                ('crop_Sowing', models.CharField(max_length=300)),
                ('crop_Harvest', models.CharField(max_length=200)),
                ('crop_Soil', models.CharField(max_length=300)),
                ('crop_Water', models.CharField(max_length=300)),
                ('crop_Seed_rate', models.CharField(max_length=300)),
                ('crop_Fertilizer', models.CharField(max_length=300)),
                ('crop_Problems', models.CharField(max_length=300)),
                ('crop_Yield', models.CharField(max_length=300)),
            ],
        ),
    ]
