# Generated by Django 5.2.10 on 2026-02-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0095_agricultureguidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agricultureguidance',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
