# Generated by Django 5.2.10 on 2026-02-18 06:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0096_agricultureguidance_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agricultureguidance',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='slider_content',
            name='second_line_text',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
