# Generated by Django 5.2.10 on 2026-02-18 06:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0097_alter_agricultureguidance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_content',
            name='first_line_text',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
