# Generated by Django 5.2.11 on 2026-02-18 07:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0098_alter_slider_content_first_line_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrochemical',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
