# Generated by Django 5.2.11 on 2026-02-18 07:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ikhedut', '0099_alter_agrochemical_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrochemical',
            name='description',
            field=ckeditor.fields.RichTextField(max_length='150'),
        ),
    ]
